### ISSUE TITLE
Updates from ld48 ?

### ISSUE THREAD

**Issue by anisse** [Healthire/rust-game-bootstrap#1]
I fell in love with the simple architecture of you ld48 entry, and that's how I found this repository. I was wondering if you had considered updating the bootstrap with any fixes from the ld48 entry (are there even any ? I wasn't sure looking at the repo).

**Comment by HexyWitch** [comment]
Oh yeah sorry, I've been meaning to do that actually but I forgot about it entirely. There are a few small things I fixed like the audio and I added some stuff to the graphics API. I'll look into backporting that stuff. Sorry I didn't see this until the *eve of LD49* lol.

**Comment by HexyWitch** [comment]
I have backported the stuff from LD48 into this project. I only did some brief testing but this should add support for texture framebuffers and fix audio.

I only did some brief testing. If you try it out and it works let me know!

**Comment by anisse** [comment]
Thanks a lot, it really wasn't urgent, more of a question. I'll be sure to give you feedback as soon as I use it.

**Comment by HexyWitch** [comment]
Cool, I'll close this then. Thanks for reminding me to do this!
